"""
Pydantic schemas for App Automation Agent.

This module consolidates all schemas used by the app automation tools.
"""

# Team schemas
from .team_schemas import (
    APIError,
    CreateTeamRequest,
    CreateTeamResponse,
    GetTeamInvitationsResponse,
    GetTeamResponse,
    InviteTeamMemberRequest,
    InviteTeamMemberResponse,
    ListTeamsResponse,
    Team,
    TeamInvitation,
    TeamMember,
    TeamRole,
    TeamWithMembers,
    UpdateTeamMemberRequest,
    UpdateTeamMemberResponse,
    UpdateTeamRequest,
    UpdateTeamResponse,
    User,
)

# Form schemas
from .form_schemas import (
    ConditionalAction,
    ConditionalOperator,
    ConditionalRule,
    CreateFormInput,
    CreateFormRequest,
    CreateFormResponse,
    CreateProgramInput,
    CreateProgramResponse,
    CreateProgramWithFormInput,
    DeleteProgramInput,
    DynamicFormConfig,
    DynamicFormField,
    DynamicFormFieldProps,
    DynamicFormStep,
    FieldType,
    FieldValidationRules,
    FormConfigResponse,
    FormFieldInput,
    FormListItem,
    FormListResponse,
    FormStepInput,
    GetProgramInput,
    GetProgramResponse,
    ProgramListItem,
    ProgramListResponse,
    SelectOption,
    SubmissionConfig,
    SubmissionMethod,
    UpdateFormInput,
    UpdateFormRequest,
    UpdateFormResponse,
    UpdateProgramInput,
    UpdateProgramResponse,
    convert_simplified_to_full_config,
    format_form_config_for_display,
    generate_field_id,
    generate_step_id,
)

# Review schemas
from .review_schemas import (
    AIEvaluation,
    Applicant,
    ApplicantsListResponse,
    CriterionScore,
    DataSource,
    FormCriteria,
    FormCriteriaListResponse,
    FormInfo,
    GetMyVotesInput,
    GetReviewQueueInput,
    GetSubmissionDetailsInput,
    GetSubmissionForReviewInput,
    GetSubmissionForReviewResponse,
    ListApplicantsInput,
    ListProgramApplicantsInput,
    MilestoneAnswer,
    MyVotesResponse,
    ProgramBudget,
    ProgramInfo,
    ProgramStats,
    ProgramStatsResponse,
    ReviewQueueResponse,
    ReviewStatus,
    ReviewerInfo,
    ScoringRules,
    SearchApplicationsInput,
    SubmissionDetail,
    SubmissionForReview,
    SubmissionReviewStatus,
    SubmissionWithEvaluationResponse,
    TeamInfo,
    TeamMember as ReviewTeamMember,
    TiebreakerInput,
    TiebreakerResponse,
    UpdateApplicantStatusInput,
    UpdateStatusResponse,
    UserInfo,
    Vote,
    VoteCounts,
    VoteInput,
    VoteResponse,
    VoteType,
    VoteWithContext,
    VoteWithReviewer,
)

# Note: Perspective schemas have been moved to src/agent/multi_perspective/types.py
# Import from there or from perspective_tools.py for tool inputs

__all__ = [
    # Team schemas
    "APIError",
    "CreateTeamRequest",
    "CreateTeamResponse",
    "GetTeamInvitationsResponse",
    "GetTeamResponse",
    "InviteTeamMemberRequest",
    "InviteTeamMemberResponse",
    "ListTeamsResponse",
    "Team",
    "TeamInvitation",
    "TeamMember",
    "TeamRole",
    "TeamWithMembers",
    "UpdateTeamMemberRequest",
    "UpdateTeamMemberResponse",
    "UpdateTeamRequest",
    "UpdateTeamResponse",
    "User",
    # Form schemas
    "ConditionalAction",
    "ConditionalOperator",
    "ConditionalRule",
    "CreateFormInput",
    "CreateFormRequest",
    "CreateFormResponse",
    "CreateProgramInput",
    "CreateProgramResponse",
    "CreateProgramWithFormInput",
    "DeleteProgramInput",
    "DynamicFormConfig",
    "DynamicFormField",
    "DynamicFormFieldProps",
    "DynamicFormStep",
    "FieldType",
    "FieldValidationRules",
    "FormConfigResponse",
    "FormFieldInput",
    "FormListItem",
    "FormListResponse",
    "FormStepInput",
    "GetProgramInput",
    "GetProgramResponse",
    "ProgramListItem",
    "ProgramListResponse",
    "SelectOption",
    "SubmissionConfig",
    "SubmissionMethod",
    "UpdateFormInput",
    "UpdateFormRequest",
    "UpdateFormResponse",
    "UpdateProgramInput",
    "UpdateProgramResponse",
    "convert_simplified_to_full_config",
    "format_form_config_for_display",
    "generate_field_id",
    "generate_step_id",
    # Review schemas
    "AIEvaluation",
    "Applicant",
    "ApplicantsListResponse",
    "CriterionScore",
    "DataSource",
    "FormCriteria",
    "FormCriteriaListResponse",
    "FormInfo",
    "GetMyVotesInput",
    "GetReviewQueueInput",
    "GetSubmissionDetailsInput",
    "GetSubmissionForReviewInput",
    "GetSubmissionForReviewResponse",
    "ListApplicantsInput",
    "ListProgramApplicantsInput",
    "MilestoneAnswer",
    "MyVotesResponse",
    "ProgramBudget",
    "ProgramInfo",
    "ProgramStats",
    "ProgramStatsResponse",
    "ReviewQueueResponse",
    "ReviewStatus",
    "ReviewerInfo",
    "ScoringRules",
    "SearchApplicationsInput",
    "SubmissionDetail",
    "SubmissionForReview",
    "SubmissionReviewStatus",
    "SubmissionWithEvaluationResponse",
    "TeamInfo",
    "ReviewTeamMember",
    "TiebreakerInput",
    "TiebreakerResponse",
    "UpdateApplicantStatusInput",
    "UpdateStatusResponse",
    "UserInfo",
    "Vote",
    "VoteCounts",
    "VoteInput",
    "VoteResponse",
    "VoteType",
    "VoteWithContext",
    "VoteWithReviewer",
    # Note: Perspective schemas moved to src/agent/multi_perspective/
]

